### PR TITLE
Initial script for getting ingress cookie automatically via selenium

### PR DESCRIPTION
**Pull request by bschultz**
This is an initial version for getting ingress cookie automatically via selenium.

Currently only supports Chrome, which needs to be installed.
Tested only on Mac.

Could be improved by supporting other browsers, Facebook login and maybe some more

### CODE REVIEW

**Comment by gopeine** [comment]
Tested and works with Chrome on Ubuntu for now. Thx

**Comment by acocalypso** [comment]
so this will not work on headless servers right?

**Comment by bschultz** [comment]
Pretty sure it will, because Selenium is running the Browser in headless mode

**Comment by acocalypso** [comment]
Then I'll give it a try

**Comment by acocalypso** [comment]
I checked it out and its not working on ubuntu 18.04 LTS with chromium

`~/intelwatcher$ ../intelwatcher_env/bin/python3 selenium_get_ingress_cookie.py
Initializing...
/bin/sh: 1: chromium: not found

[WDM] - Current chromium version is 83.0.4103
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - There is no [linux64] chromedriver for browser 83.0.4103 in cache
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/home/aco/.wdm/drivers/chromedriver/linux64/83.0.4103.39]
Login to Google via Stackoverflow
Enter username...
Enter password...
Waiting for login...
Login to Intel Ingress
Traceback (most recent call last):
  File "selenium_get_ingress_cookie.py", line 124, in <module>
    get_ingress_cookie(config)
  File "selenium_get_ingress_cookie.py", line 98, in get_ingress_cookie
    driver.find_element(By.ID, 'profileIdentifier').click()
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="profileIdentifier"]"}
  (Session info: headless chrome=83.0.4103.61)
`

**Comment by gopeine** [comment]
@apocalypso like i already wrote, it only works with chrome for now under Ubuntu

**Comment by acocalypso** [comment]
I tried it with chrome now and its not working for me with the same issue:

`Initializing...

[WDM] - Current google-chrome version is 83.0.4103
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - Driver [/home/aco/.wdm/drivers/chromedriver/linux64/83.0.4103.39/chromedriver] found in cache
Login to Google via Stackoverflow
Enter username...
Enter password...
Waiting for login...
Login to Intel Ingress
Traceback (most recent call last):
  File "selenium_get_ingress_cookie.py", line 124, in <module>
    get_ingress_cookie(config)
  File "selenium_get_ingress_cookie.py", line 98, in get_ingress_cookie
    driver.find_element(By.ID, 'profileIdentifier').click()
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/aco/intelwatcher_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="profileIdentifier"]"}
  (Session info: headless chrome=83.0.4103.116)`

**Comment by gopeine** [comment]
That looks good It did login to google only intel failed... could be too much attempts in short time 🤷🏻‍♂️

**Comment by acocalypso** [comment]
im having this on all 3 browser, firefox, chrome and chromium.
Login to google works but intel is failing on all 3 with
```elenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="profileIdentifier"]"}```

**Comment by bschultz** [comment]
> im having this on all 3 browser, firefox, chrome and chromium.
> Login to google works but intel is failing on all 3 with
> `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="profileIdentifier"]"}`
> 
> I guess google security kicked in.

Yes, I debugged it here and google wants to confirm identity with SMS 😞

**Comment by bschultz** [comment]
Closing this PR because it's now part of the auto-cookie branch which can be used until it's in master 😉

**Pull request closed without merging**
